### ISSUE TITLE
How to implement a basic 3D player controller

### ISSUE THREAD

**Issue by LaylConway** [rustgd/rhusics#80]
Looking over the docs and examples I'm at a bit of a loss on how to implement a basic player controller.
In other engines this is generally implemented as a capsule with constraints on rotation so it doesn't fall over.

**Comment by Rhuagh** [comment]
Constraints do not exist yet in rhusics. You could perhaps emulate the same behavior by adding infinite inertia around the Z and X axis in local coordinates. For capsule support look at `Capsule` in `collision-rs`.

**Comment by LaylConway** [comment]
Thanks, yea that should work for my purposes
