### ISSUE TITLE
Help with Rhusics + Specs + GGEZ

### ISSUE THREAD

**Issue by rafaeldelboni** [rustgd/rhusics#85]
I dunno where to ask for help implementing Rhusics, so I opened this ticket, I'm sorry if I did wrong.

I'm having problems trying to setup a minimal hello world using [GGEZ + Specs + Rhusics.](https://github.com/rafaeldelboni/ggez-specs-rhusics-hello-world)

The problem I'm having is in the following line:
https://github.com/rafaeldelboni/ggez-specs-rhusics-hello-world/blob/master/src/systems.rs#L34
As you can see, I'm applying for the force to the body, but it doesn't change it's position, looks like I'm missing something in the Rhusics configuration, the world seems frozen.

The example is quite simple: 3 squares, one is static, another one moving alone and the last one is controlled by the arrow keys.
You can [see here](https://github.com/rafaeldelboni/ggez-specs-hello-world/) something similar implemented with textboxes and without physics.

Any help would be really appreciated 😃

**Comment by Rhuagh** [comment]
You're not updating DeltaTime.

**Comment by rafaeldelboni** [comment]
Thanks!!!

My mistake was using `dt.as_secs() as f32` as DeltaTime source and I didn't knew it does not return the fractions, so I was updating the DeltaTime with `0.0` all the time.

This commit fixed it: 
https://github.com/rafaeldelboni/ggez-specs-rhusics-hello-world/commit/0cca9ca2455163461d17b90faefe0187017f8b0b
